<?php

namespace Database\Seeders;

use App\Models\Contractor;
use Illuminate\Database\Seeder;

class ContractorSeeder extends Seeder
{
    public function run(): void
    {
        $contractors = [
            '*18 Remodel - Ron',
            '*18 Remodel Inc. - Alvaro',
            '*18 Remodel Inc.-Martin',
            '*A&L Green Home Inc',
            '*Airtest Guru',
            '*All About Shower Glass And More Inc',
            '*All In 1 Remodeling',
            '*All Star Construction Inc',
            '*ALR Remodeling',
            '*AM PM Restoration & Construction Inc.',
            '*Amazon A',
            '*Ameriflex Mortgage',
            '*APD Smart Home & Wiring',
            '*Arevalos Appraisal Solutions',
            "*Avila's Cabinets",
            '*Best Buy',
            '*Build Force',
            '*Cali First Remodel Inc',
            '*Contractors Warehouse',
            '*Designs By Origami',
            '*DG Lumber Group INC',
            '*DHY Enterprises',
            '*E And E',
            '*FedEx Office',
            '*Francisco 18 Remodel',
            '*Frederico Countertop',
            '*Future Vision Remodeling',
            '*G-Tech Smart Remodeling',
            '*Geissler Engineering',
            '*Gibertos Flooring Services',
            '*Green Empire Builder Inc',
            '*Gringo - Rafael Builders',
            '*Gringo DHY',
            '*Haim Azulay (David)',
            '*Home Depot',
            '*John Mold Testing',
            '*KWW Kitchen Cabinets & Bath',
            '*KZ Kitchen Cabinets & Stone Inc',
            '*Lowes Home Improvement',
            '*Marciano Zion',
            "*McCurley's Floor Center Inc.",
            '*McLaughlin Concrete',
            '*Mike Engineer',
            '*Miscellaneous / Other',
            '*Muller Construction Supply',
            '*Ohad - 18 Remodel',
            '*Pacific Stone Tile & Marble',
            '*Permit City Fee',
            '*Permits By Daniel',
            '*Power Electrical Service Inc',
            '*Prime Dumpster Incorporated Inc',
            '*Rafael Builders',
            '*Rafael Builders - Hodaya',
            '*Rafael Builders - Hodaya Nn',
            '*Rafael Builders - Oded',
            '*Rafael Builders - Ron',
            '*Ramon Renderos',
            '*Registered Agent Solutions Inc',
            '*Rodriguez Custom Construction',
            '*San Jose Heating & Cooling',
            '*SBH Construction Inc.',
            '*Silicon Valley Granite',
            '*Sivan Windows And Doors',
            '*SM Electric Services Corp',
            '*Specialty Builders',
            '*Square CC Transfer',
            '*The Right Choice Home Remodeling',
            '*Top Pros Construction',
            '*US Marketing & Funds Inc',
            '*Vision Builders',
            '*Werner Lopez',
            '*Zion Marciano',
            '18 Remodel - Jose',
            '18 Remodel Inc.',
            '888 ENVIRONMENTAL',
            'A1 Elite Air Condition Inc',
            'All Things Interior',
            'ATTIC KINGS INC',
            'Best Roofing LA',
            'CAL-BREEZE HEATING & AIR CONDITIONING LLC',
            'California Roofline',
            'De Angelo Inc.',
            'EA Construction Inc.',
            'Emergency Rooter & Plumbing',
            'FHQ Electric Inc.',
            'Floor And Decor',
            'ISLD Business & Marketing Services',
            'Jade Electric - Tim',
            'JMA General Construction',
            'MD Builders',
            'Melikson Garage Door',
            'NEMA Roofing Solutions',
            'NK HOME CONSTRUCTION INC',
            'One & Only Electrical',
            'Paragon Roofing And Remodeling Inc',
            'Professional Plumbing Services',
            'REACTIC RESTORATION',
            'SILVERLINE HOME REMODELING INC',
            'SOLIR ELECTRIC',
        ];

        foreach ($contractors as $contractor) {
            $contractor = ltrim($contractor, '*');

            Contractor::query()->firstOrCreate(
                ['contractor' => $contractor],
                [
                    'address' => '',
                    'zip' => 0,
                    'city' => '',
                    'state' => '',
                    'email' => '',
                    'phone' => 0,
                    'license' => null,
                    'lic_expire' => null,
                    'worker_comp' => null,
                    'insurance_expire' => null,
                ],
            );
        }
    }
}
